CREATE TABLE IF NOT EXISTS "users" (
	"id" varchar(1024) PRIMARY KEY NOT NULL,
	"first_name" varchar(128) NOT NULL,
	"last_name" varchar(128) NOT NULL,
	"email" varchar(320) NOT NULL,
	"phone_number" varchar(20) NOT NULL,
	"recommand_score" numeric(5, 2),
	"user_type" "user_types" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "posts" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "posts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner_id" varchar(256) NOT NULL,
	"title" varchar(1024) NOT NULL,
	"category" "post_categories" NOT NULL,
	"description" varchar(1024) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"registration_start" timestamp with time zone DEFAULT now() NOT NULL,
	"registration_end" timestamp with time zone NOT NULL,
	"is_open" boolean DEFAULT true NOT NULL,
	"required_people" integer,
	"media_url" varchar(1024)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "post_requests" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "post_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"post_owner_id" varchar NOT NULL,
	"joiner_id" varchar NOT NULL,
	"requested_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "access_to_infos" (
	"post_id" integer NOT NULL,
	"volunteer_id" varchar(256) NOT NULL,
	CONSTRAINT "access_to_infos_post_id_volunteer_id_pk" PRIMARY KEY("post_id","volunteer_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "conversations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"content" varchar(1024) NOT NULL,
	"sendAt" timestamp with time zone DEFAULT now() NOT NULL,
	"sender_id" varchar(256) NOT NULL,
	"conversation_id" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar NOT NULL,
	"message" varchar(256) NOT NULL,
	"send_at" timestamp with time zone DEFAULT now() NOT NULL
);
